### ISSUE TITLE
Does not start when merged with gitlab fig.yml

### ISSUE THREAD

**Issue by jar349** [sameersbn/docker-gitlab-ci#17]
I'm trying to merge the fig.yml from your gitlab repo with the fig.yml with this repo.

Here's my fig.yml:
```
postgresql:
    image: sameersbn/postgresql:9.1-1
    environment:
        - DB_USER=gitlab
        - DB_PASS=secretpassword
        - DB_NAME=gitlabhq_production
gitlab:
    image: sameersbn/gitlab:7.7.2
    links:
        - redis:redisio
        - postgresql:postgresql
    ports:
        - "10080:80"
        - "10022:22"
redis:
    image: sameersbn/redis:latest
ci:
    image: sameersbn/gitlab-ci:5.4.2
    links:
        - redis:redisio
        - postgresql:postgresql
        - gitlab:gitlab
    ports:
        - "10081:80"
    environment:
        - GITLAB_CI_HOST=localhost:10081
        - GITLAB_URL=http://localhost:10080
        - GITLAB_APP_ID='<removed>'
        - GITLAB_APP_SECRET='<removed>'
```

When I run `sudo fig up` I get:
```
ci_1         | Waiting for database server to accept connections
ci_1         | Migrating database...
ci_1         | rake aborted!
ci_1         | Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 3 column 5
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
ci_1         | /home/gitlab_ci/gitlab-ci/config/initializers/1_settings.rb:32:in `<top (required)>'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:223:in `load'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:223:in `block in load'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:214:in `load_dependency'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:223:in `load'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/engine.rb:608:in `each'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/engine.rb:608:in `block in <class:Engine>'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/initializable.rb:30:in `instance_exec'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/initializable.rb:30:in `run'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/initializable.rb:55:in `block in run_initializers'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/initializable.rb:44:in `each'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/initializable.rb:44:in `tsort_each_child'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/initializable.rb:54:in `run_initializers'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/application.rb:215:in `initialize!'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/railtie/configurable.rb:30:in `method_missing'
ci_1         | /home/gitlab_ci/gitlab-ci/config/environment.rb:5:in `<top (required)>'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:229:in `require'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:229:in `block in require'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:214:in `load_dependency'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:229:in `require'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/application.rb:189:in `require_environment!'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.0.10/lib/rails/application.rb:260:in `block in run_tasks_blocks'
ci_1         | Tasks: TOP => db:migrate => environment
ci_1         | (See full trace by running task with --trace)
gitlab_ci_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping gitlab_gitlab_1...
Stopping gitlab_redis_1...
Stopping gitlab_postgresql_1...

```
