### ISSUE TITLE
Can't Authorize Gitlab CI

### ISSUE THREAD

**Issue by mirzap** [sameersbn/docker-gitlab-ci#18]
Hi, I have problem when I try to authorize an app:

![selection_046](https://cloud.githubusercontent.com/assets/991967/6677906/93fabc28-cc34-11e4-88ac-ced591388b7a.png)

here is log from /var/log/gitlab-ci/gitlab-ci/production.log

```
Completed 302 Found in 4ms (ActiveRecord: 0.5ms)
Started GET "/user_sessions/callback?code=f28bd4306840601bc25e8a16b2ac474bab70a151f47d5b4333cfdba698768b1a" for 146.255.155.77 at 2015-03-16 22:32:13 +0000
Processing by UserSessionsController#callback as HTML
  Parameters: {"code"=>"f28bd4306840601bc25e8a16b2ac474bab70a151f47d5b4333cfdba698768b1a"}
Completed 500 Internal Server Error in 14ms

Faraday::ConnectionFailed (Connection refused - connect(2) for "mygitlabhost.be" port 10081):
  app/controllers/user_sessions_controller.rb:18:in `callback'

```

**Comment by sameersbn** [comment]
@mirzap I see that the redirection is trying to connect to http://mygitlabhost.be:10081. Is that correct.

Please share your run commands for starting gitlab and ci.

**Comment by mirzap** [comment]
Yes @sameersbn Here is my fig file:

```
postgresql:
  image: sameersbn/postgresql:latest
  environment:
    - DB_USER=redmine
    - DB_PASS=redpass
    - DB_NAME=redmine,gitlab,gitlabci
    - PSQL_TRUST_LOCALNET=true
  volumes:
    - ./data/postgresql:/var/lib/postgresql
  ports:
    - "5432:5432"
gitlab:
  image: sameersbn/gitlab:7.8.4
  links:
   - redis:redisio
   - postgresql:postgresql
  environment:
    - DB_USER=redmine
    - DB_PASS=redpass
    - DB_NAME=gitlab
    - SMTP_DOMAIN=smtp.domain
    - SMTP_HOST=smtp.host
    - SMTP_PORT=587
    - SMTP_USER=smtp.user
    - SMTP_PASS=smtp.pass
    - SMTP_STARTTLS=true
    - GITLAB_HOST=mygitlabhost.be
    - GITLAB_PORT=10081
    - GITLAB_EMAIL=my.email
    - REDMINE_URL=http://myredmineurl.be:10080
  volumes:
    - ./data/gitlab:/home/git/data
  ports:
   - "10081:80"
   - "10022:22"
redmine:
  image: sameersbn/redmine:2.6.2
  links:
    - postgresql:postgresql
  environment:
    - DB_USER=redmine
    - DB_PASS=redpass
    - DB_NAME=redmine
    - NGINX_MAX_UPLOAD_SIZE=120m
    - SMTP_DOMAIN=smtp.domain
    - SMTP_HOST=smtp.host
    - SMTP_PORT=587
    - SMTP_USER=smtp.user
    - SMTP_PASS=smtp.pass
    - SMTP_STARTTLS=true
  volumes:
    - ./data/redmine:/home/redmine/data
  volumes_from:
    - project_gitlab_1
  ports:
    - "10080:80"
redis:
  image: sameersbn/redis:latest
ci:
  image: sameersbn/gitlab-ci:7.8.4
  links:
   - redis:redisio
   - postgresql:postgresql
  environment:
    - DB_USER=redmine
    - DB_PASS=redpass
    - DB_NAME=gitlabci
    - GITLAB_APP_ID=gitlab.app.id
    - GITLAB_APP_SECRET=gitlab.app.secret
    - GITLAB_URL=http://mygitlaburl.be:10081/
    - SMTP_DOMAIN=smtp.domain
    - SMTP_HOST=smtp.host
    - SMTP_PORT=587
    - SMTP_USER=smtp.user
    - SMTP_PASS=smtp.pass
    - SMTP_STARTTLS=true
  volumes:
    - ./data/gitlab_ci:/home/gitlab_ci/data
  ports:
    - "10082:80"
```
