### ISSUE TITLE
500 We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by Z3roCoder** [sameersbn/docker-gitlab-ci#36]
Why do I get this error? I have set everything up correctly according to https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/gitlab-ci/README.md yet I get this error. I have no idea what data to provide either so... Someone help please?

**Comment by Ablu** [comment]
I get this error too after I hit `Login with GitLab` and hitting `Authorize` on the dialog on the gitlab page.

**Comment by sameersbn** [comment]
@Z3roCoder @Ablu Please refer to my comment https://github.com/sameersbn/docker-gitlab-ci/issues/28#issuecomment-102944598 for a possible fix.

**Comment by Z3roCoder** [comment]
None of any of those things helped.

Commands I am calling both docker-compose.yml's with: 
```
docker-compose up
```

Gitlab docker-compose.yml:
```
    gitlab:
  image: sameersbn/gitlab:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  external_links:
    - maildev_maildev_1:maildev
  ports:
    - "10080:80"
    - "10022:22"
  expose:
    - "10080"
  environment:
    - TZ=Asia/Kolkata
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=maildev
    - SMTP_HOST=maildev
    - SMTP_PORT=25
#    - SMTP_USER=null
#    - SMTP_PASS=null
    - SMTP_STARTTLS=false
    - SMTP_AUTHENTICATION=login
    - GITLAB_TIMEZONE=Kolkata
    - GITLAB_HOST=my-domain.com
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=22
    - GITLAB_EMAIL=my@email.com
    - GITLAB_EMAIL_REPLY_TO=my@email.com
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=04:00
    - GITLAB_RELATIVE_URL_ROOT=/gitlab
  volumes:
    - /srv/docker/gitlab/gitlab/data:/home/git/data
    - /srv/docker/logs/gitlab:/var/log/gitlab
```

Gitlab-CI docker-compose.yml:
```
ci:
  image: sameersbn/gitlab-ci:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  external_links:
    - maildev_maildev_1:maildev
    - gitlab_gitlab_1
  ports:
    - "10081:80"
#  net: "host"
  environment:
    - TZ=Asia/Kolkata
    - GITLAB_URL=http://192.168.16.133:10080/gitlab
    - GITLAB_APP_ID=fa0718e9ef9122245fe1c6c7e3a98d80d41fdf822f243743d179b18f2ceb1046
    - GITLAB_APP_SECRET=8f137aa1a5febebd4fb7a9a00ce77a2b1debb286e3ac7dc7c8e3bd8adf6c6a70
    - GITLAB_CI_HOST=localhost
    - GITLAB_CI_RELATIVE_URL_ROOT=/gitlabci
    - GITLAB_CI_PORT=10081
    - GITLAB_CI_EMAIL=ci@example.com
    - GITLAB_CI_SUPPORT=support@example.com
    - GITLAB_CI_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_CI_NOTIFY_PUSHER=false
    - GITLAB_CI_BACKUPS=daily
    - GITLAB_CI_BACKUP_TIME=01:00
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=maildev
    - SMTP_HOST=maildev
    - SMTP_PORT=25
#    - SMTP_USER=mailer@example.com
#    - SMTP_PASS=password
    - SMTP_STARTTLS=false
    - SMTP_AUTHENTICATION=login
  volumes:
    - /srv/docker/gitlab-ci/gitlab-ci:/home/gitlab_ci/data
```
