### ISSUE TITLE
Issue starting with docker-compose

### ISSUE THREAD

**Issue by WillSkates** [sameersbn/docker-gitlab-ci#38]
I attempted to start the service using the docker-compose.yml file in the repo. I can't get an instance up and running. Each time I try to curl to localhost:10081 I get 'Connection reset by peer'.

After using
docker-compose run ci /bin/bash
and typing
wget localhost
or
wget 127.0.0.1

I get
--2015-06-30 15:52:54--  http://localhost/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:80... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.

Attempting to run /sbin/entrypoint.sh from within the container also gives me:
sed: -e expression #1, char 26: unknown option to `s'

I have modified my docker-compose.yml slightly and tried again. Here's a copy

postgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab_ci
    - DB_PASS=password
    - DB_NAME=gitlab_ci_production
  volumes:
    - /srv/docker/gitlab-ci/postgresql:/var/lib/postgresql
redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab-ci/redis:/var/lib/redis
ci:
  image: sameersbn/gitlab-ci:7.12.0
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10081:80"
  environment:
    - TZ=Europe/London
    - GITLAB_URL=http://x.x.com
    - GITLAB_APP_ID=x
    - GITLAB_APP_SECRET=x
    - GITLAB_CI_HOST=localhost
    - GITLAB_CI_PORT=10081
    - GITLAB_CI_EMAIL=will@stuffby.ws
    - GITLAB_CI_SUPPORT=will@stuffby.ws
    - GITLAB_CI_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_CI_NOTIFY_PUSHER=false
    - GITLAB_CI_BACKUPS=daily
    - GITLAB_CI_BACKUP_TIME=01:00
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
  volumes:
    - /srv/docker/gitlab-ci/gitlab-ci:/home/gitlab_ci/data

**Comment by sameersbn** [comment]
@WillSkates I have had no issue running gitlab-ci using your docker compose file

```yaml
postgresql:
  image: sameersbn/postgresql:9.4-1
  environment:
    - DB_USER=gitlab_ci
    - DB_PASS=password
    - DB_NAME=gitlab_ci_production
  volumes:
    - /srv/docker/gitlab-ci/postgresql:/var/lib/postgresql
redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab-ci/redis:/var/lib/redis
ci:
  image: sameersbn/gitlab-ci:7.12.0
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10081:80"
  environment:
    - TZ=Europe/London
    - GITLAB_URL=http://labcoat.stuffby.ws
    - GITLAB_APP_ID=x
    - GITLAB_APP_SECRET=x
    - GITLAB_CI_HOST=localhost
    - GITLAB_CI_PORT=10081
    - GITLAB_CI_EMAIL=will@stuffby.ws
    - GITLAB_CI_SUPPORT=will@stuffby.ws
    - GITLAB_CI_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_CI_NOTIFY_PUSHER=false
    - GITLAB_CI_BACKUPS=daily
    - GITLAB_CI_BACKUP_TIME=01:00
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
  volumes:
    - /srv/docker/gitlab-ci/gitlab-ci:/home/gitlab_ci/data
```

I have no issue running `curl http://localhost:10081`

Couple of things to note.
 - Allow Gitlab-CI some time to start. You can keep an eye on the logs
 - If you are using boot2docker, then you should use the VM's ip address instead of localhost
